#!/usr/bin/env bash
set -e

basedir=$(cd "$(dirname "$0")" && pwd -P)

fail() {
    local expected="$1"; shift
    local actual="$1"; shift
    cat <<___
FAILURE:
Expected: $expected
  Actual: $actual
 Message: $*
___
    exit 1
}

cd "$basedir"
[[ $1 = -C ]] && { shift; rm -rf .build; }
. ./activate

FLASK_APP=server/app.py flask run & flaskpid=$!
trap "kill $flaskpid" 0
sleep 1

expected='<p> Hello Bingo !</p>'
actual=$(curl -s http://127.0.0.1:5000/hello/Bingo)
[[ $actual =~ $expected ]] || fail \
    "$expected in" "$actual" "Request of /hello/Bingo"
